# Generated by Django 4.2.6 on 2024-02-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0005_post_content_post_is_alumni_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
