# Generated by Django 4.2.6 on 2024-02-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0010_remove_post_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_name', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('public_post', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
