# Generated by Django 4.2.6 on 2024-02-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0013_alumnipost_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Verified',
        ),
    ]
