# Generated by Django 4.2.6 on 2024-02-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0015_user_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_college',
            new_name='is_student',
        ),
    ]
