# Generated by Django 5.0.1 on 2024-04-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0025_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Work',
            field=models.TextField(max_length=800),
        ),
    ]
