# Generated by Django 5.0.1 on 2024-04-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0026_alter_user_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Github',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
