# Generated by Django 5.0.1 on 2024-04-07 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0028_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnipost',
            old_name='Alumni',
            new_name='author',
        ),
    ]
