# Generated by Django 5.0.6 on 2024-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0031_remove_user_admin_alter_alumnipost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='About',
            field=models.TextField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='Branch',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Work',
            field=models.TextField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='Year_Joined',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
