# Generated by Django 5.0.6 on 2024-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0035_alter_user_full_name_alumniprofile_donation_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='referred_students',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='success_story',
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='Education',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='current_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='current_company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='current_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='is_available_for_mentorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('linkedin', 'LinkedIn')], default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='previous_companies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='publications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='successful_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
