# Generated by Django 5.0.6 on 2024-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0037_remove_studentprofile_alumni_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodprincipalprofile',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
