# Generated by Django 5.0.6 on 2024-10-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0040_alumnipost_comments_count_alumnipost_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnipost',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='alumnipost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='alumnipost',
            name='shares_count',
        ),
        migrations.AddField(
            model_name='alumnipost',
            name='DocUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alumnipost',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
