# Generated by Django 5.0.6 on 2024-10-04 03:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0041_remove_alumnipost_comments_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HodPrincipalPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('tag', models.CharField(default='', max_length=255)),
                ('Image', models.ImageField(blank=True, default='default/def.jpeg', upload_to='images')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('DocUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible_to_students', models.BooleanField(default=True)),
                ('is_visible_to_alumni', models.BooleanField(default=True)),
                ('is_visible_to_public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
