# Generated by Django 5.0.6 on 2024-10-05 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0043_remove_hodprincipalpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='publications',
        ),
        migrations.CreateModel(
            name='AluminiJobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('skillsNeeded', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.alumniprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
