# Generated by Django 5.0.6 on 2024-10-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0045_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniexperience',
            name='alumni_profile',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='alumnipost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='alumnipost',
            name='is_visible_to_alumni',
        ),
        migrations.RemoveField(
            model_name='alumnipost',
            name='is_visible_to_public',
        ),
        migrations.RemoveField(
            model_name='alumnipost',
            name='is_visible_to_students',
        ),
        migrations.RemoveField(
            model_name='alumnipost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='is_available_for_mentorship',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='resume_url',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='successful_referrals',
        ),
        migrations.RemoveField(
            model_name='hodprincipalpost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='hodprincipalpost',
            name='is_visible_to_alumni',
        ),
        migrations.RemoveField(
            model_name='hodprincipalpost',
            name='is_visible_to_public',
        ),
        migrations.RemoveField(
            model_name='hodprincipalpost',
            name='is_visible_to_students',
        ),
        migrations.RemoveField(
            model_name='hodprincipalpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_available_for_internship',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume_url',
        ),
        migrations.AlterField(
            model_name='hodprincipalpost',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='newApp.hodprincipalprofile'),
        ),
        migrations.DeleteModel(
            name='AluminiJobPost',
        ),
        migrations.DeleteModel(
            name='AlumniExperience',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
