# Generated by Django 5.0.6 on 2024-10-05 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0046_remove_alumniexperience_alumni_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodprincipalpost',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
