# Generated by Django 5.0.6 on 2024-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0048_alter_alumnipost_id_alter_alumniprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
