# Generated by Django 5.0.6 on 2024-10-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0049_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
