# Generated by Django 5.0.6 on 2024-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0050_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='current_year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
