# Generated by Django 5.0.6 on 2024-10-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0051_alter_studentprofile_current_year_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_year',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Education',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
