# Generated by Django 5.0.6 on 2024-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0052_remove_alumniprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='Heading',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Heading',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
