# Generated by Django 5.0.6 on 2024-10-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0053_alumniprofile_heading_studentprofile_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
