# Generated by Django 5.0.6 on 2024-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0056_user_portfolio_link_user_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram')], default='email', max_length=50),
        ),
    ]
