# Generated by Django 5.0.6 on 2024-10-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0057_alter_alumniprofile_preferred_contact_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('mobile', 'Mobile'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram')], default='email', max_length=50),
        ),
    ]
