# Generated by Django 5.0.6 on 2024-10-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0058_alter_alumniprofile_preferred_contact_method'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
