# Generated by Django 5.0.6 on 2024-10-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0060_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(default=0),
        ),
    ]
