# Generated by Django 5.0.6 on 2024-10-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0061_alter_user_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='graduation_month',
            field=models.IntegerField(default=0),
        ),
    ]
