# Generated by Django 5.0.6 on 2024-10-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0062_user_graduation_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='College',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
