# Generated by Django 5.0.6 on 2024-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0063_remove_user_college_remove_user_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduation_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(),
        ),
    ]
