# Generated by Django 5.0.6 on 2024-10-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0066_alter_alumnipost_content_alter_alumnipost_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnipost',
            name='DocUrl',
            field=models.URLField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='alumnipost',
            name='image_url',
            field=models.URLField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='Education',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='Heading',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='achievements',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='current_city',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='current_company_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='current_country',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='industry',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='job_title',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='previous_companies',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hodprincipalpost',
            name='DocUrl',
            field=models.URLField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='hodprincipalpost',
            name='image_url',
            field=models.URLField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='hodprincipalprofile',
            name='designation',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='Education',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='Heading',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_year_of_study',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='About',
            field=models.TextField(default='-', max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='Branch',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Github',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Work',
            field=models.TextField(default='-', max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='Year_Joined',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='portfolio_link',
            field=models.URLField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume_link',
            field=models.URLField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='-', max_length=150, unique=True),
        ),
    ]
