# Generated by Django 5.0.6 on 2024-10-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0068_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
