# Generated by Django 5.0.6 on 2024-10-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0072_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portfolio_link',
            field=models.CharField(blank=True, default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume_link',
            field=models.CharField(blank=True, default='-', max_length=500),
        ),
    ]
