# Generated by Django 5.0.6 on 2024-10-18 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0073_alter_user_portfolio_link_alter_user_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_year_of_study',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='About',
            field=models.TextField(blank=True, default='-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='Github',
            field=models.CharField(blank=True, default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='Work',
            field=models.TextField(blank=True, default='-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='Year_Joined',
            field=models.CharField(blank=True, default='-', max_length=4, validators=[django.core.validators.MinValueValidator(1983), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_month',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1983), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, default='-', max_length=500),
        ),
    ]
