# Generated by Django 5.0.6 on 2024-10-18 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0074_alter_alumniprofile_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Year_Joined',
            field=models.IntegerField(blank=True, default=0, max_length=4, validators=[django.core.validators.MinValueValidator(1983), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
