# Generated by Django 5.0.6 on 2024-10-20 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0076_alter_user_year_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduation_month',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1983), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
