# Generated by Django 5.0.6 on 2024-10-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0078_alter_alumnipost_docurl_alter_alumnipost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduation_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
