# Generated by Django 5.0.6 on 2024-10-29 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0080_hodprincipalpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_id', models.CharField(max_length=255)),
                ('fourth_year_marksheet', models.ImageField(blank=True, null=True, upload_to='documents/marksheets/')),
                ('lc', models.ImageField(blank=True, null=True, upload_to='documents/lc/')),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='documents/id_cards/')),
                ('graduation_certificate', models.ImageField(blank=True, null=True, upload_to='documents/graduation_certificates/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
