# Generated by Django 5.0.6 on 2024-10-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0082_remove_alumnicredentials_linkedin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Year_Joined',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
