# Generated by Django 5.0.6 on 2024-11-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0083_alter_user_year_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAlumniDirectRegistration',
            field=models.BooleanField(default=False),
        ),
    ]
