# Generated by Django 5.0.6 on 2024-11-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0084_user_isalumnidirectregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniCredentials',
        ),
    ]
