# Generated by Django 5.0.6 on 2024-11-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0085_delete_alumnicredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_allowedToJoinAlumni',
            field=models.BooleanField(default=False),
        ),
    ]
