# Generated by Django 5.0.6 on 2024-11-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0086_user_is_allowedtojoinalumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_allowedToAccessLinkedinScrappingTab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_allowedToAccessSettings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_allowedToAddAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
