# Generated by Django 5.0.6 on 2024-11-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0087_user_is_allowedtoaccesslinkedinscrappingtab_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_allowedToAccessLinkedinScrappingTab',
            new_name='is_allowedToAccessPostRequestTab',
        ),
    ]
