# Generated by Django 5.0.6 on 2024-11-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0088_rename_is_allowedtoaccesslinkedinscrappingtab_user_is_allowedtoaccesspostrequesttab'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnipost',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
