# Generated by Django 5.0.6 on 2024-11-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0089_alumnipost_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnipost',
            name='DocUrl',
            field=models.CharField(blank=True, default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='alumnipost',
            name='image_url',
            field=models.CharField(blank=True, default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='hodprincipalpost',
            name='DocUrl',
            field=models.CharField(blank=True, default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='hodprincipalpost',
            name='image_url',
            field=models.CharField(blank=True, default='N/A', max_length=500),
        ),
    ]
