# Generated by Django 5.0.6 on 2024-11-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0090_alter_alumnipost_docurl_alter_alumnipost_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnipost',
            name='Image',
            field=models.ImageField(blank=True, default='default/def.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hodprincipalpost',
            name='Image',
            field=models.ImageField(blank=True, default='default/def.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.ImageField(blank=True, default='default/def.jpg', upload_to='images'),
        ),
    ]
