# Generated by Django 5.0.6 on 2024-11-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0091_alter_alumnipost_image_alter_hodprincipalpost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portfolio_web',
            field=models.CharField(blank=True, default='N/A', max_length=500),
        ),
    ]
