# Generated by Django 5.0.6 on 2024-11-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0092_user_portfolio_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portfolio_web',
        ),
    ]
