# Generated by Django 5.0.6 on 2025-03-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0093_remove_user_portfolio_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_allowedToAccessPostRequestTab',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_allowedToAccessSettings',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_allowedToAddAdmin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_allowedToJoinAlumni',
            field=models.BooleanField(default=True),
        ),
    ]
