# Generated by Django 5.0.6 on 2025-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0094_alter_user_is_allowedtoaccesspostrequesttab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_allowedToAccessPostRequestTab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_allowedToAccessSettings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_allowedToAddAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_allowedToJoinAlumni',
            field=models.BooleanField(default=False),
        ),
    ]
