# Generated by Django 4.2.6 on 2024-02-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0007_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='default/test.png', upload_to='images'),
        ),
    ]
