# Generated by Django 4.2.6 on 2024-02-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
