# Generated by Django 4.2.6 on 2024-02-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0016_rename_is_college_user_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='College',
            field=models.CharField(choices=[('SSBT COET, Jalgaon', 'SSBT COET, Jalgaon')], default='None', max_length=80),
        ),
    ]
