# Generated by Django 5.0.1 on 2024-03-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0023_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.TextField(default='[]'),
        ),
    ]
