# Generated by Django 5.0.1 on 2024-04-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0024_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.TextField(default='{"Ids": "[]"}'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.TextField(default='{"Ids": "[]"}'),
        ),
    ]
