# Generated by Django 5.0.1 on 2024-04-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0027_user_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.TextField(default='[]'),
        ),
    ]
